[package]
name = "midnight_express"
version = "0.1.0"
description = "Real-time second-price track auctions on an Ephemeral Rollup"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "midnight_express"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
custom-heap = []
custom-panic = []
anchor-debug = []

[dependencies]
anchor-lang = { version = "1.0.2" }
ephemeral-rollups-sdk = { version = "0.16.2", features = ["anchor"] }
